name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 */24 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          #  - repo
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.TOKEN }}

          # Options
          user: formidablae
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes
          plugin_discussions: yes
          # plugin_support: yes
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 50
          plugin_languages_recent_categories: markup, programming, data
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 500
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 1%
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_people: yes
          plugin_people_limit: 20
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_projects: yes
          plugin_projects_limit: 10
          # plugin_repositories: yes
          # plugin_repositories_featured: lowlighter/metrics, denoland/deno
          plugin_projects_descriptions: yes
          plugin_stars: yes
          plugin_stars_limit: 10
          plugin_traffic: yes
          repositories: 200
          repositories_batch: 200
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 60
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: no
          plugin_stargazers: yes
